### ISSUE TITLE
Reset submits all the jobs !

### ISSUE THREAD

**Issue by yanikou19** [gmatteo/abipy#108]
abirun.py path reset submits all the available jobs !

Could you please deactivate this fact, I would prefer "reset" just to reset the jobs, not to run all the available jobs. My scheduler will do it more accurately ! Or even rapid if I want to submit all.

Thanks !

**Comment by gmatteo** [comment]
I've changed the default behaviour.
Now one has to use `reset --relaunch` to relaunch the tasks in rapid mode after the reset.
