### ISSUE TITLE
monty.dict2namedtuple doesn't exist in monty 0.6.4

### ISSUE THREAD

**Issue by rousseab** [gmatteo/abipy#85]
Abipy imports monty.dict2namedtuple in a few places; this no longer exists in the 
latest (official?) version of monty. This breaks Abipy.

**Comment by gmatteo** [comment]
Hi,

The github version of abipy relies on my dev version of monty and pymatgen. 
I would suggest to fork my repositories so that you don't have to wait for
the release of a new minor version of monty/pymatgen
